# Generated by Django 5.0.3 on 2024-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Scrape',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('url', models.URLField(unique=True)),
        #         ('currency', models.CharField(max_length=10)),
        #         ('image', models.CharField(max_length=500)),
        #         ('title', models.CharField(max_length=255)),
        #         ('current_price', models.FloatField()),
        #         ('original_price', models.FloatField()),
        #         ('lowest_price', models.FloatField(blank=True, null=True)),
        #         ('highest_price', models.FloatField(blank=True, null=True)),
        #         ('average_price', models.FloatField(blank=True, null=True)),
        #         ('discount_rate', models.FloatField(blank=True, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('category', models.CharField(blank=True, max_length=255, null=True)),
        #         ('reviews_count', models.IntegerField(blank=True, null=True)),
        #         ('is_out_of_stock', models.BooleanField(default=False)),
        #         # ('users', models.JSONField(default=list)),
        #         # ('price_history', models.JSONField(default=list)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'db_table': 'users_scrape',
        #     },
        # ),
    ]
