# Generated by Django 5.0.3 on 2024-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='users',
            field=models.JSONField(default=list),
        ),
    ]
