# Generated by Django 5.0.3 on 2024-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_scrape_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
