# Generated by Django 5.0.3 on 2024-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_scrape_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='reviews_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
