# Generated by Django 5.0.3 on 2024-03-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='users_account',
        ),
    ]
