# Generated by Django 5.0.3 on 2024-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_best_sellers'),
        ('users', '0004_account_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tracks',
        ),
        migrations.AddField(
            model_name='account',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='scrape.scrape'),
        ),
    ]
