import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import AppContext from "@/components/AppContext"
import Navbar from "@/components/Navbar";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <AppContext>
          <div className="pt-16 px-8 ml-5">
            <Navbar />
            {children}
          </div>
        </AppContext>
      </body>
    </html>
  );
}
